version: "3"
services:
  bei-mssql:
    image: "g6flow-bei-mssql"
    ports:
      - "9446:9446"
    volumes:
      - ./data:/usr/bei/data
      - ./certs:/usr/bei/certs
    environment:
      BEI_COMPONENT: BEI-MSSQL
      IP: 0.0.0.0
      PORT: 9446
      CACHE_TTL: 5000
      LOG_LEVEL: debug
      APIKEY: as8da7sda6sd4as45ds67d7s7da9s090gf
      API_PREFIX: /bei-demo